### ISSUE TITLE
RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by ambethia** [survivejs/webpack-merge#53]
Hello!

The latest release `2.1.0` introduces a bug for us, rolling back to `2.0.0` is our current work around.

```
» yarn start 
yarn start v0.17.8
$ webpack-dev-server 
/Users/ambethia/Desktop/foo/node_modules/webpack-merge/lib/join-arrays.js:64
function clonePrototype(o) {
                       ^

RangeError: Maximum call stack size exceeded
    at clonePrototype (/Users/ambethia/Desktop/foo/node_modules/webpack-merge/lib/join-arrays.js:64:24)
    at baseClone (/Users/ambethia/Desktop/foo/node_modules/lodash.clonedeepwith/index.js:844:23)
    at /Users/ambethia/Desktop/foo/node_modules/lodash.clonedeepwith/index.js:897:30
    at arrayEach (/Users/ambethia/Desktop/foo/node_modules/lodash.clonedeepwith/index.js:140:9)
    at baseClone (/Users/ambethia/Desktop/foo/node_modules/lodash.clonedeepwith/index.js:891:3)
    at cloneDeepWith (/Users/ambethia/Desktop/foo/node_modules/lodash.clonedeepwith/index.js:1409:10)
    at /Users/ambethia/Desktop/foo/node_modules/webpack-merge/lib/join-arrays.js:73:19
    at Array.forEach (native)
    at clonePrototype (/Users/ambethia/Desktop/foo/node_modules/webpack-merge/lib/join-arrays.js:72:33)
    at baseClone (/Users/ambethia/Desktop/foo/node_modules/lodash.clonedeepwith/index.js:844:23)
    at /Users/ambethia/Desktop/foo/node_modules/lodash.clonedeepwith/index.js:897:30
    at arrayEach (/Users/ambethia/Desktop/foo/node_modules/lodash.clonedeepwith/index.js:140:9)
    at baseClone (/Users/ambethia/Desktop/foo/node_modules/lodash.clonedeepwith/index.js:891:3)
    at /Users/ambethia/Desktop/foo/node_modules/lodash.clonedeepwith/index.js:897:30
    at arrayEach (/Users/ambethia/Desktop/foo/node_modules/lodash.clonedeepwith/index.js:140:9)
    at baseClone (/Users/ambethia/Desktop/foo/node_modules/lodash.clonedeepwith/index.js:891:3)
error Command failed with exit code 1.
```

Here's an example of our webpack config as well: 

  https://github.com/tiy-tpa-fee/majestic-that/blob/master/webpack.config.js

Node v7.1.0 on OS X Sierra

**Comment by bebraw** [comment]
Thanks for the report. I'll investigate tomorrow in detail. Sounds like some weird recursion bit the test suite didn't capture.

**Comment by bebraw** [comment]
@ambethia I did a quick fix to break the recursion. Let me know how it goes.

I still have to figure out a good test to avoid this in the future. There's some specific case in the config that triggers it, but I can look at that in better time.

**Comment by ambethia** [comment]
I never replied, but thank you so much for the quick response and fix!

**Comment by bebraw** [comment]
No worries. Thanks. 👍
